# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/mnt/c/Users/thoma/Desktop/Programmazione/C++/Number base converter"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/mnt/c/Users/thoma/Desktop/Programmazione/C++/Number base converter"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/mnt/c/Users/thoma/Desktop/Programmazione/C++/Number base converter/CMakeFiles" "/mnt/c/Users/thoma/Desktop/Programmazione/C++/Number base converter/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/mnt/c/Users/thoma/Desktop/Programmazione/C++/Number base converter/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named numberSystemConverter

# Build rule for target.
numberSystemConverter: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 numberSystemConverter
.PHONY : numberSystemConverter

# fast build rule for target.
numberSystemConverter/fast:
	$(MAKE) -f CMakeFiles/numberSystemConverter.dir/build.make CMakeFiles/numberSystemConverter.dir/build
.PHONY : numberSystemConverter/fast

src/cli/drawCLI.o: src/cli/drawCLI.cpp.o

.PHONY : src/cli/drawCLI.o

# target to build an object file
src/cli/drawCLI.cpp.o:
	$(MAKE) -f CMakeFiles/numberSystemConverter.dir/build.make CMakeFiles/numberSystemConverter.dir/src/cli/drawCLI.cpp.o
.PHONY : src/cli/drawCLI.cpp.o

src/cli/drawCLI.i: src/cli/drawCLI.cpp.i

.PHONY : src/cli/drawCLI.i

# target to preprocess a source file
src/cli/drawCLI.cpp.i:
	$(MAKE) -f CMakeFiles/numberSystemConverter.dir/build.make CMakeFiles/numberSystemConverter.dir/src/cli/drawCLI.cpp.i
.PHONY : src/cli/drawCLI.cpp.i

src/cli/drawCLI.s: src/cli/drawCLI.cpp.s

.PHONY : src/cli/drawCLI.s

# target to generate assembly for a file
src/cli/drawCLI.cpp.s:
	$(MAKE) -f CMakeFiles/numberSystemConverter.dir/build.make CMakeFiles/numberSystemConverter.dir/src/cli/drawCLI.cpp.s
.PHONY : src/cli/drawCLI.cpp.s

src/cli/terminalSize.o: src/cli/terminalSize.cpp.o

.PHONY : src/cli/terminalSize.o

# target to build an object file
src/cli/terminalSize.cpp.o:
	$(MAKE) -f CMakeFiles/numberSystemConverter.dir/build.make CMakeFiles/numberSystemConverter.dir/src/cli/terminalSize.cpp.o
.PHONY : src/cli/terminalSize.cpp.o

src/cli/terminalSize.i: src/cli/terminalSize.cpp.i

.PHONY : src/cli/terminalSize.i

# target to preprocess a source file
src/cli/terminalSize.cpp.i:
	$(MAKE) -f CMakeFiles/numberSystemConverter.dir/build.make CMakeFiles/numberSystemConverter.dir/src/cli/terminalSize.cpp.i
.PHONY : src/cli/terminalSize.cpp.i

src/cli/terminalSize.s: src/cli/terminalSize.cpp.s

.PHONY : src/cli/terminalSize.s

# target to generate assembly for a file
src/cli/terminalSize.cpp.s:
	$(MAKE) -f CMakeFiles/numberSystemConverter.dir/build.make CMakeFiles/numberSystemConverter.dir/src/cli/terminalSize.cpp.s
.PHONY : src/cli/terminalSize.cpp.s

src/mainFolder/mainfile.o: src/mainFolder/mainfile.cpp.o

.PHONY : src/mainFolder/mainfile.o

# target to build an object file
src/mainFolder/mainfile.cpp.o:
	$(MAKE) -f CMakeFiles/numberSystemConverter.dir/build.make CMakeFiles/numberSystemConverter.dir/src/mainFolder/mainfile.cpp.o
.PHONY : src/mainFolder/mainfile.cpp.o

src/mainFolder/mainfile.i: src/mainFolder/mainfile.cpp.i

.PHONY : src/mainFolder/mainfile.i

# target to preprocess a source file
src/mainFolder/mainfile.cpp.i:
	$(MAKE) -f CMakeFiles/numberSystemConverter.dir/build.make CMakeFiles/numberSystemConverter.dir/src/mainFolder/mainfile.cpp.i
.PHONY : src/mainFolder/mainfile.cpp.i

src/mainFolder/mainfile.s: src/mainFolder/mainfile.cpp.s

.PHONY : src/mainFolder/mainfile.s

# target to generate assembly for a file
src/mainFolder/mainfile.cpp.s:
	$(MAKE) -f CMakeFiles/numberSystemConverter.dir/build.make CMakeFiles/numberSystemConverter.dir/src/mainFolder/mainfile.cpp.s
.PHONY : src/mainFolder/mainfile.cpp.s

src/numberCheck/numberCheck.o: src/numberCheck/numberCheck.cpp.o

.PHONY : src/numberCheck/numberCheck.o

# target to build an object file
src/numberCheck/numberCheck.cpp.o:
	$(MAKE) -f CMakeFiles/numberSystemConverter.dir/build.make CMakeFiles/numberSystemConverter.dir/src/numberCheck/numberCheck.cpp.o
.PHONY : src/numberCheck/numberCheck.cpp.o

src/numberCheck/numberCheck.i: src/numberCheck/numberCheck.cpp.i

.PHONY : src/numberCheck/numberCheck.i

# target to preprocess a source file
src/numberCheck/numberCheck.cpp.i:
	$(MAKE) -f CMakeFiles/numberSystemConverter.dir/build.make CMakeFiles/numberSystemConverter.dir/src/numberCheck/numberCheck.cpp.i
.PHONY : src/numberCheck/numberCheck.cpp.i

src/numberCheck/numberCheck.s: src/numberCheck/numberCheck.cpp.s

.PHONY : src/numberCheck/numberCheck.s

# target to generate assembly for a file
src/numberCheck/numberCheck.cpp.s:
	$(MAKE) -f CMakeFiles/numberSystemConverter.dir/build.make CMakeFiles/numberSystemConverter.dir/src/numberCheck/numberCheck.cpp.s
.PHONY : src/numberCheck/numberCheck.cpp.s

src/numberConversion/convertNumberFunction.o: src/numberConversion/convertNumberFunction.cpp.o

.PHONY : src/numberConversion/convertNumberFunction.o

# target to build an object file
src/numberConversion/convertNumberFunction.cpp.o:
	$(MAKE) -f CMakeFiles/numberSystemConverter.dir/build.make CMakeFiles/numberSystemConverter.dir/src/numberConversion/convertNumberFunction.cpp.o
.PHONY : src/numberConversion/convertNumberFunction.cpp.o

src/numberConversion/convertNumberFunction.i: src/numberConversion/convertNumberFunction.cpp.i

.PHONY : src/numberConversion/convertNumberFunction.i

# target to preprocess a source file
src/numberConversion/convertNumberFunction.cpp.i:
	$(MAKE) -f CMakeFiles/numberSystemConverter.dir/build.make CMakeFiles/numberSystemConverter.dir/src/numberConversion/convertNumberFunction.cpp.i
.PHONY : src/numberConversion/convertNumberFunction.cpp.i

src/numberConversion/convertNumberFunction.s: src/numberConversion/convertNumberFunction.cpp.s

.PHONY : src/numberConversion/convertNumberFunction.s

# target to generate assembly for a file
src/numberConversion/convertNumberFunction.cpp.s:
	$(MAKE) -f CMakeFiles/numberSystemConverter.dir/build.make CMakeFiles/numberSystemConverter.dir/src/numberConversion/convertNumberFunction.cpp.s
.PHONY : src/numberConversion/convertNumberFunction.cpp.s

src/numberConversion/convertToNewBase.o: src/numberConversion/convertToNewBase.cpp.o

.PHONY : src/numberConversion/convertToNewBase.o

# target to build an object file
src/numberConversion/convertToNewBase.cpp.o:
	$(MAKE) -f CMakeFiles/numberSystemConverter.dir/build.make CMakeFiles/numberSystemConverter.dir/src/numberConversion/convertToNewBase.cpp.o
.PHONY : src/numberConversion/convertToNewBase.cpp.o

src/numberConversion/convertToNewBase.i: src/numberConversion/convertToNewBase.cpp.i

.PHONY : src/numberConversion/convertToNewBase.i

# target to preprocess a source file
src/numberConversion/convertToNewBase.cpp.i:
	$(MAKE) -f CMakeFiles/numberSystemConverter.dir/build.make CMakeFiles/numberSystemConverter.dir/src/numberConversion/convertToNewBase.cpp.i
.PHONY : src/numberConversion/convertToNewBase.cpp.i

src/numberConversion/convertToNewBase.s: src/numberConversion/convertToNewBase.cpp.s

.PHONY : src/numberConversion/convertToNewBase.s

# target to generate assembly for a file
src/numberConversion/convertToNewBase.cpp.s:
	$(MAKE) -f CMakeFiles/numberSystemConverter.dir/build.make CMakeFiles/numberSystemConverter.dir/src/numberConversion/convertToNewBase.cpp.s
.PHONY : src/numberConversion/convertToNewBase.cpp.s

src/numberConversion/convertToTen.o: src/numberConversion/convertToTen.cpp.o

.PHONY : src/numberConversion/convertToTen.o

# target to build an object file
src/numberConversion/convertToTen.cpp.o:
	$(MAKE) -f CMakeFiles/numberSystemConverter.dir/build.make CMakeFiles/numberSystemConverter.dir/src/numberConversion/convertToTen.cpp.o
.PHONY : src/numberConversion/convertToTen.cpp.o

src/numberConversion/convertToTen.i: src/numberConversion/convertToTen.cpp.i

.PHONY : src/numberConversion/convertToTen.i

# target to preprocess a source file
src/numberConversion/convertToTen.cpp.i:
	$(MAKE) -f CMakeFiles/numberSystemConverter.dir/build.make CMakeFiles/numberSystemConverter.dir/src/numberConversion/convertToTen.cpp.i
.PHONY : src/numberConversion/convertToTen.cpp.i

src/numberConversion/convertToTen.s: src/numberConversion/convertToTen.cpp.s

.PHONY : src/numberConversion/convertToTen.s

# target to generate assembly for a file
src/numberConversion/convertToTen.cpp.s:
	$(MAKE) -f CMakeFiles/numberSystemConverter.dir/build.make CMakeFiles/numberSystemConverter.dir/src/numberConversion/convertToTen.cpp.s
.PHONY : src/numberConversion/convertToTen.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... numberSystemConverter"
	@echo "... src/cli/drawCLI.o"
	@echo "... src/cli/drawCLI.i"
	@echo "... src/cli/drawCLI.s"
	@echo "... src/cli/terminalSize.o"
	@echo "... src/cli/terminalSize.i"
	@echo "... src/cli/terminalSize.s"
	@echo "... src/mainFolder/mainfile.o"
	@echo "... src/mainFolder/mainfile.i"
	@echo "... src/mainFolder/mainfile.s"
	@echo "... src/numberCheck/numberCheck.o"
	@echo "... src/numberCheck/numberCheck.i"
	@echo "... src/numberCheck/numberCheck.s"
	@echo "... src/numberConversion/convertNumberFunction.o"
	@echo "... src/numberConversion/convertNumberFunction.i"
	@echo "... src/numberConversion/convertNumberFunction.s"
	@echo "... src/numberConversion/convertToNewBase.o"
	@echo "... src/numberConversion/convertToNewBase.i"
	@echo "... src/numberConversion/convertToNewBase.s"
	@echo "... src/numberConversion/convertToTen.o"
	@echo "... src/numberConversion/convertToTen.i"
	@echo "... src/numberConversion/convertToTen.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

